apiVersion: flowspec/v1alpha1
kind: ServiceSpec
metadata:
  name: user-service
  version: v2.1.0
spec:
  endpoints:
    - path: /api/users/{id}
      operations:
        - method: GET
          responses:
            statusRanges: ["2xx", "4xx"]
            aggregation: "range"
          required:
            headers: ["authorization"]
            query: []
          optional:
            headers: ["accept-language"]
            query: ["include"]
          stats:
            supportCount: 245
            firstSeen: "2025-08-01T10:00:00Z"
            lastSeen: "2025-08-10T16:30:00Z"
        - method: PUT
          responses:
            statusCodes: [200, 400, 404]
            aggregation: "exact"
          required:
            headers: ["authorization", "content-type"]
            query: []
          stats:
            supportCount: 89
            firstSeen: "2025-08-01T11:15:00Z"
            lastSeen: "2025-08-10T14:20:00Z"
        - method: DELETE
          responses:
            statusCodes: [204, 404]
            aggregation: "exact"
          required:
            headers: ["authorization"]
            query: []
          stats:
            supportCount: 34
            firstSeen: "2025-08-02T09:30:00Z"
            lastSeen: "2025-08-09T17:45:00Z"
    - path: /api/users
      operations:
        - method: GET
          responses:
            statusCodes: [200]
            aggregation: "exact"
          required:
            headers: []
            query: []
          optional:
            headers: ["authorization"]
            query: ["page", "limit", "sort", "filter"]
          stats:
            supportCount: 156
            firstSeen: "2025-08-01T08:00:00Z"
            lastSeen: "2025-08-10T18:00:00Z"
        - method: POST
          responses:
            statusCodes: [201, 400, 422]
            aggregation: "exact"
          required:
            headers: ["content-type"]
            query: []
          optional:
            headers: ["authorization"]
          stats:
            supportCount: 67
            firstSeen: "2025-08-01T10:30:00Z"
            lastSeen: "2025-08-10T15:15:00Z"
    - path: /api/users/{id}/profile
      operations:
        - method: GET
          responses:
            statusRanges: ["2xx", "4xx"]
            aggregation: "range"
          required:
            headers: ["authorization"]
            query: []
          optional:
            headers: ["accept-language"]
            query: ["fields"]
          stats:
            supportCount: 123
            firstSeen: "2025-08-01T12:00:00Z"
            lastSeen: "2025-08-10T16:45:00Z"
        - method: PUT
          responses:
            statusCodes: [200, 400, 404]
            aggregation: "exact"
          required:
            headers: ["authorization", "content-type"]
            query: []
          stats:
            supportCount: 45
            firstSeen: "2025-08-02T10:15:00Z"
            lastSeen: "2025-08-10T13:30:00Z"
    - path: /api/auth/login
      operations:
        - method: POST
          responses:
            statusCodes: [200, 401, 422]
            aggregation: "exact"
          required:
            headers: ["content-type"]
            query: []
          stats:
            supportCount: 89
            firstSeen: "2025-08-01T08:30:00Z"
            lastSeen: "2025-08-10T17:30:00Z"
    - path: /api/auth/logout
      operations:
        - method: POST
          responses:
            statusCodes: [204]
            aggregation: "exact"
          required:
            headers: ["authorization"]
            query: []
          stats:
            supportCount: 78
            firstSeen: "2025-08-01T09:00:00Z"
            lastSeen: "2025-08-10T17:00:00Z"